import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../src/components/sharedstyles'
import Cards from '../src/components/cards'
import { Customer } from '../src/data/Customer'

export default function Home() {
  const customer = new Customer(
    parseInt(process.env.CUSTOMER_ID),
    process.env.CUSTOMER_NAME,
    process.env.CUSTOMER_SECRET
  );

  // Not public
  console.log(process.env.CUSTOMER_ID);
  console.log('Customer', customer);

  // Public
  console.log(process.env.NEXT_PUBLIC_CUSTOMER_EMAIL);
  
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Description>
          Get started by editing
          <CodeTag>pages/index.tsx</CodeTag>
        </Description>

        <Cards />
      </Main>
    </Container>
  )
}
